name: Run Python Script

on:
  schedule:
    - cron: '0 15 * * *'  # Runs every day at 8:00 AM PST
  workflow_dispatch:

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run script
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
          SLACK_CHANNEL_ID: ${{ secrets.SLACK_CHANNEL_ID }}
          API_URL: ${{ vars.API_URL }}
          TIMESTAMP_FIELD: ${{ vars.TIMESTAMP_FIELD }}
          TIMEZONE: ${{ vars.TIMEZONE }}
        run: python check.py
